apiVersion: v1
kind: Service
metadata:
  name: appserver-service
spec:
  type: LoadBalancer   # Change to NodePort if running locally or no LB support
  selector:
    app: appserver
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000

