name: Build and Deploy to EKS

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout AppServer Repo
        uses: actions/checkout@v3

      - name: Set up Build Directory
        run: |
          mkdir -p build
          cd build
          echo "BUILD_HOME=$(pwd)" >> $GITHUB_ENV

      - name: Install Build Requirements
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip
          pip3 install -r requirements.txt

      - name: Configure AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2  # Change if needed

      - name: Run Release Build Script
        run: |
          sudo -E bash apprunner/tools/build_release.sh

